version: '3.6'

services:
  etcd:
    image: docker.io/bitnami/etcd:3.5
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
    volumes:
      - etcd_data:/bitnami/etcd

  factory:
    image: quay.io/apibara/sink-mongo:0.5.2
    volumes:
      - ./:/data/
    command:
      - run
      - --allow-env=/data/env_goerli
      - /data/indexer/src/factory.ts
    depends_on:
      - etcd
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      SINK_ID: factory
      PERSIST_TO_ETCD: http://etcd:2379

  nft_router:
    image: quay.io/apibara/sink-mongo:0.5.2
    volumes:
      - ./:/data/
    command:
      - run
      - --allow-env=/data/env_goerli
      - /data/indexer/src/nft_router.ts
    depends_on:
      - etcd
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      SINK_ID: nft_router
      PERSIST_TO_ETCD: http://etcd:2379

  init_db:
    build:
      context: .
      dockerfile: Dockerfile
    command:
    - init
    - --env-file
    - env_goerli
    environment:
      PYTHONUNBUFFERED: "1"

  event_processor:
    build:
      context: .
      dockerfile: Dockerfile
    command:
    - process
    - --env-file
    - env_goerli
    depends_on:
      - init_db
    environment:
      PYTHONUNBUFFERED: "1"

  position_processor:
    build:
      context: .
      dockerfile: Dockerfile
    command:
    - positions
    - --env-file
    - env_goerli
    depends_on:
      - init_db
    environment:
      PYTHONUNBUFFERED: "1"

  graphql:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
    - 8000:8000
    command:
    - graphql
    - --env-file
    - env_goerli
    depends_on:
      - init_db
    environment:
      PYTHONUNBUFFERED: "1"

volumes:
  etcd_data: