version: '3.6'
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: apibara
      MONGO_INITDB_ROOT_PASSWORD: apibara
    ports:
      - 27017:27017
    volumes:
      - ./_docker/apibara_mongodb:/data/db

  factory:
    image: quay.io/apibara/sink-mongo:0.4.10
    volumes:
      - ./:/data/
    command:
      - run
      - --allow-env=/data/env-goerli
      - /data/src/factory.ts
    depends_on:
      - mongo
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      SINK_ID: factory

  nft_router:
    image: quay.io/apibara/sink-mongo:0.4.10
    volumes:
      - ./:/data/
    command:
      - run
      - --allow-env=/data/env-goerli
      - /data/src/nft_router.ts
    depends_on:
      - mongo
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      SINK_ID: nft_router

  pools_initialize:
    image: quay.io/apibara/sink-mongo:0.4.10
    volumes:
      - ./:/data/
    command:
      - run
      - --allow-env=/data/env-goerli
      - /data/src/pools_initialize.ts
    depends_on:
      - mongo
      - factory
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      SINK_ID: pools_initialize

  pools_data:
    image: quay.io/apibara/sink-mongo:0.4.10
    volumes:
      - ./:/data/
    command:
      - run
      - --allow-env=/data/env-goerli
      - /data/src/pools_data.ts
    depends_on:
      - mongo
      - factory
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      SINK_ID: pools_data
